data_root_dir: ${oc.env:DATASET_ROOT_DIR}
dataset: "OVQA"
test_folder_name: "test.json"
val_folder_name: "validate.json"
train_folder_name: "train.json"
data_shift: "question_type"
ood_value: "Attribute Other"
train_split: "iid"
split: "iid"
model_type: "lora"

split_file: "${dataset}_test_${split}_${data_shift}_${ood_value}"
# split_file: "OVQA_test_iid_question-type_attribute-other" 
split_file_train: "${dataset}_train_${train_split}_${data_shift}_${ood_value}"
# split_file_train:  "OVQA_train_iid_question-type_attribute-other"
data_dir: ${data_root_dir}/${dataset}
model_path: ${oc.env:EXPERIMENT_ROOT_DIR}/${dataset}/${model_type}/llava-${split_file_train}-finetune_${model_type}


# set the base model with the llava_med pretrained weights
model_base: ${oc.env:LLAVA_MED_MODEL_PATH}
output_file: ${model_path}/eval/${split_file}/test_results.json
max_new_tokens: 100
num_workers: 24
batch_size: 1

# possible question types and test set counts in the dataset
# question_type       
# Abnormality      509
# Attribute Other  269
# Condition        452
# Modality         316
# Organ System     237
# PLANE            119