data_root_dir: ${oc.env:DATASET_ROOT_DIR}
dataset: "OVQA"
test_folder_name: "test.json"
val_folder_name: "validate.json"
train_folder_name: "train.json"
data_shift: "question_type"
ood_value: "Attribute Other"
train_split: "iid"
split: "iid"
model_type: "pretrained"

split_file: "${dataset}_test_${split}_${data_shift}_${ood_value}"
# split_file: "OVQA_test_iid_question-type_attribute-other" 
split_file_train: "${dataset}_train_${train_split}_${data_shift}_${ood_value}"
# split_file_train:  "OVQA_train_iid_question-type_attribute-other"
data_dir: ${data_root_dir}/${dataset}
# model_path: path_to_pretrained_model
model_path: ${oc.env:LLAVA_MED_MODEL_PATH}

# set the base model with the llava_med pretrained weights
model_base: null
output_file: ${oc.env:EXPERIMENT_ROOT_DIR}/${dataset}/${model_type}/eval/${split_file}/test_results.json 
max_new_tokens: 100
num_workers: 24
batch_size: 1