data_root_dir: ${oc.env:DATASET_ROOT_DIR}
dataset: "OVQA"
split_file: "ovqa_test_ood_question-type_attribute-other"
data_dir: ${data_root_dir}/${dataset}
split_file_train:  "ovqa_train_iid_question-type_attribute-other" # take the model checkpoint finetuned on iid train set
model_path: ${oc.env:LLAVA_MED_MODEL_PATH}

# set the base model with the llava_med pretrained weights
model_base: null
output_file: ${oc.env:EXPERIMENT_ROOT_DIR}/${dataset}/Pretrained/eval/${split_file}/test_results.json 
max_new_tokens: 100
num_workers: 24