data_root_dir: ${oc.env:DATASET_ROOT_DIR}
dataset: "OVQA"
# data_shift: "questiontype"
# ood_value: "attributeother"
# iid_ood: "ood"
# split_file: "${dataset}_test_${iid_ood}_${data_shift}_${ood_value}"
split_file: "ovqa_test_ood_question-type_attribute-other" 
data_dir: ${data_root_dir}/${dataset}
split_file_train:  "ovqa_train_iid_question-type_attribute-other" # take the model checkpoint finetuned on iid train set
model_path: ${oc.env:EXPERIMENT_ROOT_DIR}/${dataset}/LoRA/llava-${split_file_train}-finetune_lora

# set the base model with the llava_med pretrained weights
model_base: ${oc.env:LLAVA_MED_MODEL_PATH}
output_file: ${model_path}/eval/${split_file}/test_results.json
max_new_tokens: 100
num_workers: 24

# possible question types and test set counts in the dataset
# question_type       
# Abnormality      509
# Attribute Other  269
# Condition        452
# Modality         316
# Organ System     237
# PLANE            119