data_root_dir: ${oc.env:DATASET_ROOT_DIR}
dataset: "SLAKE"
test_folder_name: "test.json"
val_folder_name: "validate.json"
train_folder_name: "train.json"
data_shift: "modality"
ood_value: "X-Ray"
train_split: "iid"
split: "iid"
mod: "test"
model_type: "pretrained"
seed: 123
no_image: False
train_no_image: False

# split_file: "${dataset}_test_${split}_${data_shift}_${ood_value}"
# split_file: "SLAKE_test_iid_modality_X-Ray"
# split_file_train: "${dataset}_train_${train_split}_${data_shift}_${ood_value}"
# split_file_train:  "SLAKE_train_iid_modality_X-Ray"
data_dir: ${data_root_dir}/${dataset}
# model_path: path_to_pretrained_model
model_path: ${oc.env:LLAVA_MED_MODEL_PATH}

# set the base model with the llava_med pretrained weights
model_base: null
#output_file: ${oc.env:EXPERIMENT_ROOT_DIR}/${dataset}/${model_type}/eval/${split_file}/test_results.json
max_new_tokens: 100
num_workers: 24
batch_size: 1

# Corruption
corruption: False
corruption_probabilities: {
    'blur': 0.5,
    'brightness': 0.5,
    'noise': 0.5,
}
corruption_strength: {
    'blur':'low', 
    'brightness': 'low',
    'noise': 'low',
}