data_root_dir: ${oc.env:DATASET_ROOT_DIR}
dataset: "SLAKE"
data_shift: "modality" 
ood_value: "X-Ray"
train_split: "iid"
split: "iid"
model_type: "lora"
metric_type: "traditional_metrics"

split_file: "${dataset}_test_${split}_${data_shift}_${ood_value}"
# split_file: "SLAKE_test_iid_modality_X-Ray" 
split_file_train: "${dataset}_train_${train_split}_${data_shift}_${ood_value}"
# split_file_train:  "SLAKE_train_iid_modality_X-Ray"
data_dir: ${data_root_dir}/${dataset}
model_path: ${oc.env:EXPERIMENT_ROOT_DIR}/${dataset}/${model_type}/llava-${split_file_train}-finetune_${model_type}

# set the base model with the llava_med pretrained weights
model_base: ${oc.env:LLAVA_MED_MODEL_PATH}
model_output_file: ${model_path}/eval/${split_file}/test_results.json
metrics_file: ${model_path}/metrics/${split_file}/${metric_type}.json
averaged_metrics_file: ${model_path}/metrics/${split_file}/averaged_${metric_type}.json

