data_root_dir: ${oc.env:DATASET_ROOT_DIR}
dataset: "SLAKE"
data_shift: "modality"
ood_value: "X-Ray"
train_split: "iid"
split: "iid"
model_type: "lora"
metric_type: "traditional_metrics"

split_file: "${dataset}_test_${split}_${data_shift}_${ood_value}"
# split_file: "SLAKE_test_iid_modality_X-Ray"
split_file_train: "${dataset}_train_${train_split}_${data_shift}_${ood_value}"
# split_file_train:  "SLAKE_train_iid_modality_X-Ray"
data_dir: ${data_root_dir}/${dataset}
model_name: llava-${split_file_train}-finetune_${model_type}
exp_path: ${oc.env:EXPERIMENT_ROOT_DIR}/${dataset}/${model_type}/${model_name}

model_output_file: ${exp_path}/eval/${split_file}/test_results.json
metrics_file: ${exp_path}/eval/${split_file}/${metric_type}.json
averaged_metrics_file: ${exp_path}/eval/${split_file}/${metric_type}_averaged.json