data_root_dir: ${oc.env:DATASET_ROOT_DIR}
dataset: "SLAKE"
data_shift: "modality"
ood_value: "X-Ray"
train_split: "iid"
split: "iid"
model_type: "lora" #ia3
metric_type: ["traditional_metrics", "mistral", "mistral_closed"]
mod: "test"
seed: 123
hyperparams_model_name: seed${seed}
no_image: False
train_no_image: False
corruption: False

model_train_file: ${data_root_dir}/${dataset}/train.json
model_val_file: ${data_root_dir}/${dataset}/validate.json
model_test_file: ${data_root_dir}/${dataset}/test.json