experiment_root_dir: ${oc.env:EXPERIMENT_ROOT_DIR}
data_root_dir: ${oc.env:DATASET_ROOT_DIR}
seed: 123
output_dir: null
dataset: SLAKE
balanced: True
answer_type: OPEN
train_set: all
val_set: all
num_questions: 40
finetune_method: ia3
hyperparam_str: lr3e-2_seed123
