data_root_dir: ${oc.env:DATASET_ROOT_DIR}
dataset: "OVQA"
split_file: "ovqa_test_ood_question-type_attribute-other"
data_dir: ${data_root_dir}/${dataset}
split_file_train: "ovqa_train_iid_question-type_attribute-other" # take the model checkpoint finetuned on iid train set
model_path: ${oc.env:EXPERIMENT_ROOT_DIR}/${dataset}/LoRA/llava-${split_file_train}-finetune_lora

# set the base model with the llava_med pretrained weights
model_base: ${oc.env:LLAVA_MED_MODEL_PATH}
model_output_file: ${model_path}/eval/${split_file}/test_results.json
metrics_file: ${model_path}/metrics/${split_file}/mistral_metrics.json
averaged_metrics_file: ${model_path}/metrics/${split_file}/averaged_mistral_metrics.json