data_root_dir: ${oc.env:DATASET_ROOT_DIR}
dataset: "OVQA"
data_shift: "question-type"
ood_value: "attribute-other"
train_iid_ood: "iid"
inference_on_iid_or_ood: "iid"
model_params_from: "LoRA"
metric_type: "traditional_metrics"

split_file: "${dataset}_test_${inference_on_iid_or_ood}_${data_shift}_${ood_value}"
# split_file: "OVQA_test_iid_question-type_attribute-other" 
split_file_train: "${dataset}_train_${train_iid_ood}_${data_shift}_${ood_value}"
# split_file_train:  "OVQA_train_iid_question-type_attribute-other"
data_dir: ${data_root_dir}/${dataset}
# model_path: ${oc.env:EXPERIMENT_ROOT_DIR}/${dataset}/LoRA/llava-${split_file_train}
model_path: ${oc.env:EXPERIMENT_ROOT_DIR}/${dataset}/${model_params_from}/llava-${split_file_train}

# set the base model with the llava_med pretrained weights
model_base: ${oc.env:LLAVA_MED_MODEL_PATH}
model_output_file: ${model_path}/eval/${split_file}/test_results.json
metrics_file: ${model_path}/metrics/${split_file}/${metric_type}.json
averaged_metrics_file: ${model_path}/metrics/${split_file}/averaged_${metric_type}.json