data_root_dir: ${oc.env:DATASET_ROOT_DIR}
dataset: "Slake"
split_file: "slake_test_ood_modality_X-Ray"
data_dir: ${data_root_dir}/${dataset}
# split_file_train: "slake_train_all"
split_file_train: "slake_train_iid_modality_X-Ray" # take the model checkpoint finetuned on iid train set
model_path: ${oc.env:EXPERIMENT_ROOT_DIR}/${dataset}/LoRA/llava-${split_file_train}-finetune_lora

# set the base model with the llava_med pretrained weights
model_base: ${oc.env:LLAVA_MED_MODEL_PATH}
output_file: ${model_path}/eval/${split_file}/test_results.json
max_new_tokens: 100
num_workers: 24

model_args:
  # vision_tower: "openai/clip-vit-large-patch14-336"
  vision_tower: "openai/clip-vit-large-patch14"
  # mm_projector_type: "mlp2x_gelu"   # DANGER ZONE! This changes the architecture compared to the checkpoint...
  mm_vision_select_layer: -2        # What does this even mean?
  mm_use_im_start_end: true
  mm_use_im_patch_token: false