data_root_dir: ${oc.env:DATASET_ROOT_DIR}
dataset: "Slake"
split_file: "slake_train_all"
output_dir: ${oc.env:EXPERIMENT_ROOT_DIR}/${dataset}/LoRA


training_args:
  lora_enable: true
  lora_r: 128
  lora_alpha: 256
  mm_projector_lr: 2e-5
  image_aspect_ratio: "pad"
  group_by_modality_length: true
  bf16: true
  # output dir
  num_train_epochs: 1
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 1
  evaluation_strategy: "no"
  save_strategy: "steps"
  save_steps: 50000
  save_total_limit: 1
  learning_rate: 2e-4
  weight_decay: 0.
  warmup_ratio: 0.03
  lr_scheduler_type: "cosine"
  logging_steps: 1
  tf32: true
  model_max_length: 2048
  gradient_checkpointing: true
  dataloader_num_workers: 4
  lazy_preprocess: true

model_args:
  model_name_or_path: "liuhaotian/llava-v1.5-7b"
  version: "v1"
  vision_tower: "openai/clip-vit-large-patch14-336"
  mm_projector_type: "mlp2x_gelu"
  mm_vision_select_layer: -2
  mm_use_im_start_end: false
  mm_use_im_patch_token: false


data_args:
  image_folder: ${data_root_dir}/${dataset}